import { GoogleGenAI } from "@google/genai";
import { fileToBase64 } from "../utils";

// Initialize the API client
// Note: API Key must be provided via process.env.API_KEY
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateCompositeImage = async (
  imageFile: File,
  characterName: string,
  additionalPrompt?: string
): Promise<string> => {
  try {
    const base64Data = await fileToBase64(imageFile);
    const mimeType = imageFile.type;

    // Construct the prompt
    // We want to edit the image to add the character.
    // gemini-2.5-flash-image is capable of editing/infilling based on visual and text prompts.
    const promptText = `
      Edit this image to include ${characterName} from the Bible standing next to the person in the photo.
      
      Style guidelines:
      1. Keep the original person's appearance, lighting, and background consistent where possible, or blend them into a historical biblical setting if it fits better.
      2. ${characterName} should be depicted in a respectful, historically inspired manner typical of biblical art (robes, period-appropriate attire).
      3. The interaction should look natural, like a friendly photo or a respectful meeting.
      4. High quality, photorealistic, cinematic lighting.
      ${additionalPrompt ? `5. Additional User Request: ${additionalPrompt}` : ''}
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data
            }
          },
          {
            text: promptText
          }
        ]
      }
    });

    // Check for image in response
    // The response might contain an image part.
    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image was generated by the model.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to generate image. Please try again.");
  }
};